import React, { createContext, useState, useContext, ReactNode } from "react";

type Language = "en" | "fa" | "ru" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.services": "Services",
    "nav.testimonials": "Testimonials",
    "nav.globalCoverage": "Global Coverage",
    "nav.contact": "Contact",
    "nav.getQuote": "Get a Quote",
    
    // Hero Section
    "hero.title": "Swift, Timely, Efficient Shipping Solutions",
    "hero.subtitle": "Trusted by 1000+ companies for reliable cargo transportation across Asia and Europe with specialized refrigerated container options.",
    "hero.services": "Our Services",
    "hero.support": "24/7 Support",
    "hero.shipping": "Global Shipping",
    "hero.imageAlt": "Cargo ship transporting containers",
    "hero.imageCaption": "Efficient Logistics Solutions",
    
    // Stats Section
    "stats.title": "Our Impact in Numbers",
    "stats.subtitle": "We're proud of our track record and the trust placed in us by our customers",
    "stats.companies.number": "1000+",
    "stats.companies.title": "Satisfied Companies",
    "stats.companies.description": "Trusted by businesses across industries",
    "stats.experience.number": "15+",
    "stats.experience.title": "Years Experience",
    "stats.experience.description": "Expertise in global shipping logistics",
    "stats.continents.number": "2",
    "stats.continents.title": "Continents Covered",
    "stats.continents.description": "Seamless operations across Asia & Europe",
    "stats.support.number": "24/7",
    "stats.support.title": "Customer Support",
    "stats.support.description": "Always available to assist you",
    
    // Services Section
    "services.title": "Our Specialized Services",
    "services.subtitle": "Swift, timely, and efficient solutions tailored to your cargo transportation needs",
    "services.containers.title": "Refrigerated Containers",
    "services.containers.description": "Specialized temperature-controlled containers perfect for perishable goods, food products, and chemical API transportation.",
    "services.global.title": "Global Shipping",
    "services.global.description": "Seamless logistics services connecting Sub Continental Asia and Europe with reliable transportation networks.",
    "services.timely.title": "Timely Deliveries",
    "services.timely.description": "Punctual and efficient deliveries ensuring your cargo reaches its destination exactly when expected.",
    "services.cargo.title": "Cargo Transportation",
    "services.cargo.description": "Full-service cargo handling from pickup to delivery with careful attention to your specific requirements.",
    "services.cost.title": "Cost-Effective Plans",
    "services.cost.description": "Streamlined shipping solutions designed to maximize efficiency while reducing your overall logistics costs.",
    "services.customerSupport.title": "24/7 Customer Support",
    "services.customerSupport.description": "Round-the-clock assistance from our dedicated team to address any questions or concerns about your shipments.",
    
    // Testimonials Section
    "testimonials.title": "What Our Clients Say",
    "testimonials.subtitle": "Trusted by over 1,000 companies for reliable shipping solutions",
    "testimonials.clientLogos": "CLIENT LOGOS",
    "testimonials.person1.name": "Sarah Chen",
    "testimonials.person1.company": "Global Foods Inc.",
    "testimonials.person1.quote": "SwiftFlow's refrigerated containers have been crucial for our food exports. Their timely delivery and 24/7 support have made them an indispensable logistics partner.",
    "testimonials.person2.name": "Rahul Patel",
    "testimonials.person2.company": "PharmaConnect",
    "testimonials.person2.quote": "We trust SwiftFlow with our sensitive API shipments between Asia and Europe. Their cost-effective plans and reliable service have significantly improved our supply chain.",
    "testimonials.person3.name": "Anna Kowalski",
    "testimonials.person3.company": "European Distributors Ltd.",
    "testimonials.person3.quote": "The efficiency of SwiftFlow's operations has transformed our import process. Their attention to detail and consistent performance make them stand out in the industry.",
    
    // Global Coverage Section
    "coverage.title": "Global Coverage",
    "coverage.subtitle": "Our extensive shipping network spans across Sub Continental Asia and Europe, providing seamless logistics solutions for businesses of all sizes.",
    "coverage.mapAlt": "Global shipping map",
    "coverage.asia": "Asia Coverage",
    "coverage.europe": "Europe Coverage",
    "coverage.asiaCountries.india": "India",
    "coverage.asiaCountries.china": "China",
    "coverage.asiaCountries.japan": "Japan",
    "coverage.asiaCountries.singapore": "Singapore",
    "coverage.asiaCountries.korea": "South Korea",
    "coverage.asiaCountries.malaysia": "Malaysia",
    "coverage.europeCountries.uk": "United Kingdom",
    "coverage.europeCountries.germany": "Germany",
    "coverage.europeCountries.netherlands": "Netherlands",
    "coverage.europeCountries.france": "France",
    "coverage.europeCountries.italy": "Italy",
    "coverage.europeCountries.spain": "Spain",
    
    // Contact Form
    "contact.title": "Contact Us",
    "contact.subtitle": "Our team is available 24/7 to assist you with your shipping needs",
    "contact.getInTouch": "Get in Touch",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.successMessage": "Message sent successfully!",
    "contact.errorMessage": "Failed to send message. Please try again.",
    
    // Contact Information
    "contactInfo.title": "Contact Information",
    "contactInfo.address": "Address",
    "contactInfo.addressValue": "Kara Logistics Iranian Shipping and Air Cargo Services, unit 9, 5th, No.13, Floor, Noor Alley. Nelson Mandela BLVD Tehran, Iran",
    "contactInfo.phone": "Phone",
    "contactInfo.phoneValue": "+98 2191011477",
    "contactInfo.email": "Email",
    "contactInfo.emailValue": "info@karalogistics.com",
    "contactInfo.about": "About Us",
    "contactInfo.aboutValue": "Kara Logistics began its operations in early 2024 with a clear vision and a strong passion for the logistics, shipping, and air cargo industry. The company was formed as a collective effort by industry leaders who bring over three decades of experience in global trade, freight forwarding, and supply chain management.",
    "contactInfo.follow": "Follow Us",
    
    // Footer
    "footer.about": "Kara Logistics began its operations in early 2024 with a clear vision and a strong passion for the logistics, shipping, and air cargo industry.",
    "footer.services.title": "Services",
    "footer.services.refrigerated": "Refrigerated Containers",
    "footer.services.global": "Global Shipping",
    "footer.services.cargo": "Cargo Transportation",
    "footer.services.cost": "Cost-Effective Plans",
    "footer.services.support": "24/7 Customer Support",
    "footer.company.title": "Company",
    "footer.company.about": "About Us",
    "footer.company.why": "Why Choose Us",
    "footer.company.testimonials": "Testimonials",
    "footer.company.blog": "Blog",
    "footer.company.careers": "Careers",
    "footer.support.title": "Support",
    "footer.support.contact": "Contact Us",
    "footer.support.faq": "FAQs",
    "footer.support.track": "Track Shipment",
    "footer.support.quote": "Request a Quote",
    "footer.support.terms": "Terms & Conditions",
    "footer.copyright": "© 2025 SwiftFlow. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    
    // Language Names (for the selector)
    "language.en": "English",
    "language.fa": "فارسی",
    "language.ru": "Русский",
    "language.hi": "हिंदी"
  },
  fa: {
    // Navigation
    "nav.services": "خدمات",
    "nav.testimonials": "نظرات مشتریان",
    "nav.globalCoverage": "پوشش جهانی",
    "nav.contact": "تماس با ما",
    "nav.getQuote": "دریافت قیمت",
    
    // Hero Section
    "hero.title": "راه‌حل‌های حمل و نقل سریع، به‌موقع و کارآمد",
    "hero.subtitle": "مورد اعتماد بیش از ۱۰۰۰ شرکت برای حمل و نقل قابل اعتماد بار در سراسر آسیا و اروپا با گزینه‌های کانتینر یخچال‌دار تخصصی.",
    "hero.services": "خدمات ما",
    "hero.support": "پشتیبانی ۲۴/۷",
    "hero.shipping": "حمل و نقل جهانی",
    "hero.imageAlt": "کشتی باری در حال حمل کانتینرها",
    "hero.imageCaption": "راه‌حل‌های لجستیک کارآمد",
    
    // Stats Section
    "stats.title": "تأثیر ما در اعداد",
    "stats.subtitle": "ما به سابقه خود و اعتمادی که مشتریان ما به ما داشته‌اند افتخار می‌کنیم",
    "stats.companies.number": "+۱۰۰۰",
    "stats.companies.title": "شرکت‌های راضی",
    "stats.companies.description": "مورد اعتماد کسب و کارها در صنایع مختلف",
    "stats.experience.number": "+۱۵",
    "stats.experience.title": "سال تجربه",
    "stats.experience.description": "تخصص در لجستیک حمل و نقل جهانی",
    "stats.continents.number": "۲",
    "stats.continents.title": "قاره تحت پوشش",
    "stats.continents.description": "عملیات بی‌نقص در سراسر آسیا و اروپا",
    "stats.support.number": "۲۴/۷",
    "stats.support.title": "پشتیبانی مشتری",
    "stats.support.description": "همیشه آماده کمک به شما",
    
    // Services Section
    "services.title": "خدمات تخصصی ما",
    "services.subtitle": "راه‌حل‌های سریع، به‌موقع و کارآمد متناسب با نیازهای حمل و نقل بار شما",
    "services.containers.title": "کانتینرهای یخچال‌دار",
    "services.containers.description": "کانتینرهای تخصصی با دمای کنترل شده مناسب برای کالاهای فاسدشدنی، محصولات غذایی و حمل و نقل مواد شیمیایی API.",
    "services.global.title": "حمل و نقل جهانی",
    "services.global.description": "خدمات لجستیک بی‌نقص که آسیای زیرقاره‌ای و اروپا را با شبکه‌های حمل و نقل قابل اعتماد متصل می‌کند.",
    "services.timely.title": "تحویل به‌موقع",
    "services.timely.description": "تحویل‌های دقیق و کارآمد که اطمینان می‌دهد بار شما دقیقاً زمانی که انتظار دارید به مقصد برسد.",
    "services.cargo.title": "حمل و نقل بار",
    "services.cargo.description": "خدمات کامل حمل بار از بارگیری تا تحویل با توجه دقیق به نیازهای خاص شما.",
    "services.cost.title": "طرح‌های مقرون به صرفه",
    "services.cost.description": "راه‌حل‌های حمل و نقل ساده شده برای به حداکثر رساندن کارایی و کاهش هزینه‌های کلی لجستیک شما.",
    "services.customerSupport.title": "پشتیبانی مشتری ۲۴/۷",
    "services.customerSupport.description": "کمک شبانه‌روزی از تیم متخصص ما برای پاسخ به هر گونه سؤال یا نگرانی در مورد محموله‌های شما.",
    
    // Testimonials Section
    "testimonials.title": "مشتریان ما چه می‌گویند",
    "testimonials.subtitle": "مورد اعتماد بیش از ۱,۰۰۰ شرکت برای راه‌حل‌های حمل و نقل قابل اعتماد",
    "testimonials.clientLogos": "لوگوهای مشتریان",
    "testimonials.person1.name": "سارا چن",
    "testimonials.person1.company": "گلوبال فودز اینک.",
    "testimonials.person1.quote": "کانتینرهای یخچال‌دار سوئیفت‌فلو برای صادرات مواد غذایی ما بسیار مهم بوده‌اند. تحویل به‌موقع و پشتیبانی ۲۴/۷ آنها آنها را به یک شریک لجستیکی ضروری تبدیل کرده است.",
    "testimonials.person2.name": "راهول پاتل",
    "testimonials.person2.company": "فارماکانکت",
    "testimonials.person2.quote": "ما به سوئیفت‌فلو برای محموله‌های حساس API بین آسیا و اروپا اعتماد می‌کنیم. طرح‌های مقرون به صرفه و خدمات قابل اعتماد آنها به طور قابل توجهی زنجیره تأمین ما را بهبود بخشیده است.",
    "testimonials.person3.name": "آنا کووالسکی",
    "testimonials.person3.company": "توزیع‌کنندگان اروپایی",
    "testimonials.person3.quote": "کارایی عملیات سوئیفت‌فلو فرآیند واردات ما را متحول کرده است. توجه به جزئیات و عملکرد مداوم آنها باعث می‌شود در این صنعت برجسته باشند.",
    
    // Global Coverage Section
    "coverage.title": "پوشش جهانی",
    "coverage.subtitle": "شبکه گسترده حمل و نقل ما در سراسر آسیای زیرقاره‌ای و اروپا گسترده است و راه‌حل‌های لجستیکی بی‌نقص را برای کسب و کارهای همه اندازه‌ها فراهم می‌کند.",
    "coverage.mapAlt": "نقشه حمل و نقل جهانی",
    "coverage.asia": "پوشش آسیا",
    "coverage.europe": "پوشش اروپا",
    "coverage.asiaCountries.india": "هند",
    "coverage.asiaCountries.china": "چین",
    "coverage.asiaCountries.japan": "ژاپن",
    "coverage.asiaCountries.singapore": "سنگاپور",
    "coverage.asiaCountries.korea": "کره جنوبی",
    "coverage.asiaCountries.malaysia": "مالزی",
    "coverage.europeCountries.uk": "بریتانیا",
    "coverage.europeCountries.germany": "آلمان",
    "coverage.europeCountries.netherlands": "هلند",
    "coverage.europeCountries.france": "فرانسه",
    "coverage.europeCountries.italy": "ایتالیا",
    "coverage.europeCountries.spain": "اسپانیا",
    
    // Contact Form
    "contact.title": "تماس با ما",
    "contact.subtitle": "تیم ما ۲۴/۷ برای کمک به نیازهای حمل و نقل شما در دسترس است",
    "contact.getInTouch": "در تماس باشید",
    "contact.name": "نام",
    "contact.email": "ایمیل",
    "contact.subject": "موضوع",
    "contact.message": "پیام",
    "contact.send": "ارسال پیام",
    "contact.sending": "در حال ارسال...",
    "contact.successMessage": "پیام با موفقیت ارسال شد!",
    "contact.errorMessage": "ارسال پیام ناموفق بود. لطفا دوباره تلاش کنید.",
    
    // Contact Information
    "contactInfo.title": "اطلاعات تماس",
    "contactInfo.address": "آدرس",
    "contactInfo.addressValue": "Kara Logistics Iranian Shipping and Air Cargo Services, unit 9, طبقه ۵، پلاک ۱۳، کوچه نور، بلوار نلسون ماندلا، تهران، ایران",
    "contactInfo.phone": "تلفن",
    "contactInfo.phoneValue": "+98 2191011477",
    "contactInfo.email": "ایمیل",
    "contactInfo.emailValue": "info@karalogistics.com",
    "contactInfo.about": "درباره ما",
    "contactInfo.aboutValue": "کارا لجستیک فعالیت خود را در اوایل سال ۲۰۲۴ با چشم‌اندازی روشن و اشتیاق قوی به صنعت لجستیک، کشتیرانی و حمل و نقل هوایی آغاز کرد. این شرکت به عنوان تلاشی جمعی توسط رهبران صنعت تشکیل شد که بیش از سه دهه تجربه در تجارت جهانی، حمل و نقل بین‌المللی و مدیریت زنجیره تأمین دارند.",
    "contactInfo.follow": "ما را دنبال کنید",
    
    // Footer
    "footer.about": "کارا لجستیک فعالیت خود را در اوایل سال ۲۰۲۴ با چشم‌اندازی روشن و اشتیاق قوی به صنعت لجستیک، کشتیرانی و حمل و نقل هوایی آغاز کرد.",
    "footer.services.title": "خدمات",
    "footer.services.refrigerated": "کانتینرهای یخچال‌دار",
    "footer.services.global": "حمل و نقل جهانی",
    "footer.services.cargo": "حمل و نقل بار",
    "footer.services.cost": "طرح‌های مقرون به صرفه",
    "footer.services.support": "پشتیبانی مشتری ۲۴/۷",
    "footer.company.title": "شرکت",
    "footer.company.about": "درباره ما",
    "footer.company.why": "چرا ما را انتخاب کنید",
    "footer.company.testimonials": "نظرات مشتریان",
    "footer.company.blog": "وبلاگ",
    "footer.company.careers": "فرصت‌های شغلی",
    "footer.support.title": "پشتیبانی",
    "footer.support.contact": "تماس با ما",
    "footer.support.faq": "سوالات متداول",
    "footer.support.track": "پیگیری محموله",
    "footer.support.quote": "درخواست قیمت",
    "footer.support.terms": "شرایط و ضوابط",
    "footer.copyright": "© ۲۰۲۵ سوئیفت‌فلو. تمامی حقوق محفوظ است.",
    "footer.privacy": "سیاست حریم خصوصی",
    "footer.terms": "شرایط خدمات",
    "footer.cookies": "سیاست کوکی‌ها",
    
    // Language Names (for the selector)
    "language.en": "English",
    "language.fa": "فارسی",
    "language.ru": "Русский",
    "language.hi": "हिंदी"
  },
  ru: {
    // Navigation
    "nav.services": "Услуги",
    "nav.testimonials": "Отзывы",
    "nav.globalCoverage": "Глобальное покрытие",
    "nav.contact": "Контакты",
    "nav.getQuote": "Получить расценки",
    
    // Hero Section
    "hero.title": "Быстрые, своевременные, эффективные решения для доставки",
    "hero.subtitle": "Нам доверяют более 1000 компаний для надежной транспортировки грузов по Азии и Европе со специализированными вариантами рефрижераторных контейнеров.",
    "hero.services": "Наши услуги",
    "hero.support": "Поддержка 24/7",
    "hero.shipping": "Глобальная доставка",
    "hero.imageAlt": "Грузовое судно, перевозящее контейнеры",
    "hero.imageCaption": "Эффективные логистические решения",
    
    // Stats Section
    "stats.title": "Наше влияние в цифрах",
    "stats.subtitle": "Мы гордимся нашими достижениями и доверием, оказанным нам нашими клиентами",
    "stats.companies.number": "1000+",
    "stats.companies.title": "Довольных компаний",
    "stats.companies.description": "Доверие предприятий из разных отраслей",
    "stats.experience.number": "15+",
    "stats.experience.title": "Лет опыта",
    "stats.experience.description": "Опыт в глобальной логистике доставки",
    "stats.continents.number": "2",
    "stats.continents.title": "Охваченных континента",
    "stats.continents.description": "Бесперебойные операции по Азии и Европе",
    "stats.support.number": "24/7",
    "stats.support.title": "Поддержка клиентов",
    "stats.support.description": "Всегда готовы помочь вам",
    
    // Services Section
    "services.title": "Наши специализированные услуги",
    "services.subtitle": "Быстрые, своевременные и эффективные решения, адаптированные к вашим потребностям в транспортировке грузов",
    "services.containers.title": "Рефрижераторные контейнеры",
    "services.containers.description": "Специализированные контейнеры с контролируемой температурой, идеально подходящие для скоропортящихся товаров, пищевых продуктов и транспортировки химических веществ API.",
    "services.global.title": "Глобальная доставка",
    "services.global.description": "Бесперебойные логистические услуги, соединяющие субконтинентальную Азию и Европу с надежными транспортными сетями.",
    "services.timely.title": "Своевременные доставки",
    "services.timely.description": "Пунктуальные и эффективные доставки, обеспечивающие прибытие вашего груза в пункт назначения точно в срок.",
    "services.cargo.title": "Транспортировка грузов",
    "services.cargo.description": "Полное обслуживание по обработке грузов от погрузки до доставки с тщательным вниманием к вашим конкретным требованиям.",
    "services.cost.title": "Экономически эффективные планы",
    "services.cost.description": "Упрощенные решения доставки, разработанные для максимальной эффективности при снижении общих логистических затрат.",
    "services.customerSupport.title": "Поддержка клиентов 24/7",
    "services.customerSupport.description": "Круглосуточная помощь от нашей преданной команды для решения любых вопросов или проблем, связанных с вашими отправлениями.",
    
    // Testimonials Section
    "testimonials.title": "Что говорят наши клиенты",
    "testimonials.subtitle": "Доверие более 1000 компаний к надежным решениям доставки",
    "testimonials.clientLogos": "ЛОГОТИПЫ КЛИЕНТОВ",
    "testimonials.person1.name": "Сара Чен",
    "testimonials.person1.company": "Global Foods Inc.",
    "testimonials.person1.quote": "Рефрижераторные контейнеры SwiftFlow имеют решающее значение для нашего экспорта продуктов питания. Их своевременная доставка и круглосуточная поддержка сделали их незаменимым логистическим партнером.",
    "testimonials.person2.name": "Рахул Патель",
    "testimonials.person2.company": "PharmaConnect",
    "testimonials.person2.quote": "Мы доверяем SwiftFlow наши чувствительные отправки API между Азией и Европой. Их экономичные планы и надежный сервис значительно улучшили нашу цепочку поставок.",
    "testimonials.person3.name": "Анна Ковальски",
    "testimonials.person3.company": "European Distributors Ltd.",
    "testimonials.person3.quote": "Эффективность операций SwiftFlow преобразовала наш процесс импорта. Их внимание к деталям и постоянная производительность выделяют их в отрасли.",
    
    // Global Coverage Section
    "coverage.title": "Глобальное покрытие",
    "coverage.subtitle": "Наша обширная сеть доставки охватывает Субконтинентальную Азию и Европу, обеспечивая безупречные логистические решения для бизнеса любого размера.",
    "coverage.mapAlt": "Карта глобальной доставки",
    "coverage.asia": "Покрытие Азии",
    "coverage.europe": "Покрытие Европы",
    "coverage.asiaCountries.india": "Индия",
    "coverage.asiaCountries.china": "Китай",
    "coverage.asiaCountries.japan": "Япония",
    "coverage.asiaCountries.singapore": "Сингапур",
    "coverage.asiaCountries.korea": "Южная Корея",
    "coverage.asiaCountries.malaysia": "Малайзия",
    "coverage.europeCountries.uk": "Великобритания",
    "coverage.europeCountries.germany": "Германия",
    "coverage.europeCountries.netherlands": "Нидерланды",
    "coverage.europeCountries.france": "Франция",
    "coverage.europeCountries.italy": "Италия",
    "coverage.europeCountries.spain": "Испания",
    
    // Contact Form
    "contact.title": "Связаться с нами",
    "contact.subtitle": "Наша команда доступна 24/7, чтобы помочь вам с вашими потребностями в доставке",
    "contact.getInTouch": "Связаться",
    "contact.name": "Имя",
    "contact.email": "Эл. почта",
    "contact.subject": "Тема",
    "contact.message": "Сообщение",
    "contact.send": "Отправить сообщение",
    "contact.sending": "Отправка...",
    "contact.successMessage": "Сообщение успешно отправлено!",
    "contact.errorMessage": "Не удалось отправить сообщение. Пожалуйста, попробуйте снова.",
    
    // Contact Information
    "contactInfo.title": "Контактная информация",
    "contactInfo.address": "Адрес",
    "contactInfo.addressValue": "Kara Logistics Иранские услуги морских и авиаперевозок, блок 9, 5-й этаж, No.13, Noor Alley. Бульвар Нельсона Манделы, Тегеран, Иран",
    "contactInfo.phone": "Телефон",
    "contactInfo.phoneValue": "+98 2191011477",
    "contactInfo.email": "Эл. почта",
    "contactInfo.emailValue": "info@karalogistics.com",
    "contactInfo.about": "О нас",
    "contactInfo.aboutValue": "Компания Kara Logistics начала свою деятельность в начале 2024 года с четким видением и сильной страстью к индустрии логистики, морских и авиаперевозок. Компания была сформирована как коллективные усилия лидеров отрасли, которые обладают более чем тридцатилетним опытом в области международной торговли, экспедирования грузов и управления цепочками поставок.",
    "contactInfo.follow": "Подписывайтесь на нас",
    
    // Footer
    "footer.about": "Компания Kara Logistics начала свою деятельность в начале 2024 года с четким видением и сильной страстью к индустрии логистики, морских и авиаперевозок.",
    "footer.services.title": "Услуги",
    "footer.services.refrigerated": "Рефрижераторные контейнеры",
    "footer.services.global": "Глобальная доставка",
    "footer.services.cargo": "Транспортировка грузов",
    "footer.services.cost": "Экономичные планы",
    "footer.services.support": "Поддержка клиентов 24/7",
    "footer.company.title": "Компания",
    "footer.company.about": "О нас",
    "footer.company.why": "Почему выбирают нас",
    "footer.company.testimonials": "Отзывы",
    "footer.company.blog": "Блог",
    "footer.company.careers": "Карьера",
    "footer.support.title": "Поддержка",
    "footer.support.contact": "Связаться с нами",
    "footer.support.faq": "ЧЗВ",
    "footer.support.track": "Отследить отправление",
    "footer.support.quote": "Запросить расценки",
    "footer.support.terms": "Условия и положения",
    "footer.copyright": "© 2025 SwiftFlow. Все права защищены.",
    "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия обслуживания",
    "footer.cookies": "Политика использования файлов cookie",
    
    // Language Names (for the selector)
    "language.en": "English",
    "language.fa": "فارسی",
    "language.ru": "Русский",
    "language.hi": "हिंदी"
  },
  hi: {
    // Navigation
    "nav.services": "सेवाएं",
    "nav.testimonials": "प्रशंसापत्र",
    "nav.globalCoverage": "वैश्विक कवरेज",
    "nav.contact": "संपर्क करें",
    "nav.getQuote": "कोटेशन प्राप्त करें",
    
    // Hero Section
    "hero.title": "त्वरित, समय पर, कुशल शिपिंग समाधान",
    "hero.subtitle": "विशेष रेफ्रिजरेटेड कंटेनर विकल्पों के साथ एशिया और यूरोप में विश्वसनीय कार्गो परिवहन के लिए 1000+ कंपनियों द्वारा विश्वसनीय।",
    "hero.services": "हमारी सेवाएं",
    "hero.support": "24/7 सहायता",
    "hero.shipping": "वैश्विक शिपिंग",
    "hero.imageAlt": "कंटेनर ले जाने वाला कार्गो जहाज",
    "hero.imageCaption": "कुशल लॉजिस्टिक्स समाधान",
    
    // Stats Section
    "stats.title": "संख्याओं में हमारा प्रभाव",
    "stats.subtitle": "हम अपने ट्रैक रिकॉर्ड और हमारे ग्राहकों द्वारा हम पर रखे गए विश्वास पर गर्व करते हैं",
    "stats.companies.number": "1000+",
    "stats.companies.title": "संतुष्ट कंपनियां",
    "stats.companies.description": "विभिन्न उद्योगों में व्यवसायों द्वारा विश्वसनीय",
    "stats.experience.number": "15+",
    "stats.experience.title": "वर्षों का अनुभव",
    "stats.experience.description": "वैश्विक शिपिंग लॉजिस्टिक्स में विशेषज्ञता",
    "stats.continents.number": "2",
    "stats.continents.title": "महाद्वीप कवर किए गए",
    "stats.continents.description": "एशिया और यूरोप में निर्बाध संचालन",
    "stats.support.number": "24/7",
    "stats.support.title": "ग्राहक सहायता",
    "stats.support.description": "आपकी सहायता के लिए हमेशा उपलब्ध",
    
    // Services Section
    "services.title": "हमारी विशेष सेवाएं",
    "services.subtitle": "आपके कार्गो परिवहन की जरूरतों के अनुरूप त्वरित, समय पर और कुशल समाधान",
    "services.containers.title": "रेफ्रिजरेटेड कंटेनर",
    "services.containers.description": "नाशवान वस्तुओं, खाद्य उत्पादों और रासायनिक API परिवहन के लिए विशेष तापमान-नियंत्रित कंटेनर।",
    "services.global.title": "वैश्विक शिपिंग",
    "services.global.description": "विश्वसनीय परिवहन नेटवर्क के साथ उपमहाद्वीपीय एशिया और यूरोप को जोड़ने वाली निर्बाध लॉजिस्टिक्स सेवाएं।",
    "services.timely.title": "समय पर डिलीवरी",
    "services.timely.description": "समय पर और कुशल डिलीवरी यह सुनिश्चित करती है कि आपका कार्गो ठीक उसी समय अपने गंतव्य तक पहुंचे जब अपेक्षित हो।",
    "services.cargo.title": "कार्गो परिवहन",
    "services.cargo.description": "आपकी विशिष्ट आवश्यकताओं पर ध्यान देने के साथ पिकअप से डिलीवरी तक पूर्ण-सेवा कार्गो हैंडलिंग।",
    "services.cost.title": "किफायती योजनाएं",
    "services.cost.description": "आपकी समग्र लॉजिस्टिक्स लागत को कम करते हुए दक्षता को अधिकतम करने के लिए सुव्यवस्थित शिपिंग समाधान।",
    "services.customerSupport.title": "24/7 ग्राहक सहायता",
    "services.customerSupport.description": "आपके शिपमेंट के बारे में किसी भी प्रश्न या चिंता का समाधान करने के लिए हमारी समर्पित टीम से चौबीसों घंटे सहायता।",
    
    // Testimonials Section
    "testimonials.title": "हमारे ग्राहक क्या कहते हैं",
    "testimonials.subtitle": "विश्वसनीय शिपिंग समाधानों के लिए 1,000 से अधिक कंपनियों द्वारा विश्वसनीय",
    "testimonials.clientLogos": "क्लाइंट लोगो",
    "testimonials.person1.name": "सारा चेन",
    "testimonials.person1.company": "ग्लोबल फूड्स इंक.",
    "testimonials.person1.quote": "स्विफ्टफ्लो के रेफ्रिजरेटेड कंटेनर हमारे खाद्य निर्यात के लिए महत्वपूर्ण रहे हैं। उनकी समय पर डिलीवरी और 24/7 सहायता ने उन्हें एक अनिवार्य लॉजिस्टिक्स भागीदार बना दिया है।",
    "testimonials.person2.name": "राहुल पटेल",
    "testimonials.person2.company": "फार्माकनेक्ट",
    "testimonials.person2.quote": "हम एशिया और यूरोप के बीच अपने संवेदनशील API शिपमेंट के लिए स्विफ्टफ्लो पर भरोसा करते हैं। उनकी किफायती योजनाओं और विश्वसनीय सेवा ने हमारी आपूर्ति श्रृंखला में काफी सुधार किया है।",
    "testimonials.person3.name": "अन्ना कोवाल्स्की",
    "testimonials.person3.company": "यूरोपियन डिस्ट्रीब्यूटर्स लिमिटेड",
    "testimonials.person3.quote": "स्विफ्टफ्लो के संचालन की कार्यकुशलता ने हमारी आयात प्रक्रिया को बदल दिया है। विवरण पर उनका ध्यान और लगातार प्रदर्शन उन्हें उद्योग में अलग करता है।",
    
    // Global Coverage Section
    "coverage.title": "वैश्विक कवरेज",
    "coverage.subtitle": "हमारा व्यापक शिपिंग नेटवर्क उपमहाद्वीपीय एशिया और यूरोप में फैला हुआ है, जो सभी आकारों के व्यवसायों के लिए निर्बाध लॉजिस्टिक समाधान प्रदान करता है।",
    "coverage.mapAlt": "वैश्विक शिपिंग मानचित्र",
    "coverage.asia": "एशिया कवरेज",
    "coverage.europe": "यूरोप कवरेज",
    "coverage.asiaCountries.india": "भारत",
    "coverage.asiaCountries.china": "चीन",
    "coverage.asiaCountries.japan": "जापान",
    "coverage.asiaCountries.singapore": "सिंगापुर",
